log:
  loglevel: info
dns:
  servers:
  - https+local://8.8.8.8/dns-query
inbounds:
- port: 8080
  protocol: trojan
  settings:
    clients:
    - password: "bfca87a6-09c0-438c-8135-7b4603047afd"
  streamSettings:
    network: ws
    wsSettings:
      path: qwe
      
  protocol: vmess
  settings:
    clients:
    - id: bfca87a6-09c0-438c-8135-7b4603047afd
  streamSettings:
    network: ws
    wsSettings:
      path: qwe

    
  protocol: vless
  settings:
    decryption: none
    clients:
    - id: bfca87a6-09c0-438c-8135-7b4603047afd
  streamSettings:
    network: ws
    wsSettings:
      path: qwe

 
  protocol: shadowsocks
  settings:
    password: "bfca87a6-09c0-438c-8135-7b4603047afd"
    method: chacha20-ietf-poly1305
    ivcheck: true
  streamSettings:
    network: ws
    wsSettings:
      path: qwe
  sniffing:
    enabled: true
    destOverride:
    - http
    - tls
    - quic
    
outbounds:
- protocol: freedom
  tag: direct
  settings:
    domainStrategy: UseIPv4
